# _config.yml
theme: jekyll-theme-minimal
remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ARM332 homepage
author: André
description: Bookmark this to keep an eye on my project updates!
